CommerceStorage/ProgettoECommerce/Controllers/ClienteController.cs
using ECommerceLibrary;
using ProgettoECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoECommerce.Controllers
{
    public class ClienteController : Controller
    {
        private IClienteSqlProvider _clienteSqlProvider;

        public ClienteController()
        {

            _clienteSqlProvider = new ClientiSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);

        }
       
        public ActionResult Index()
        {
            var clienti = _clienteSqlProvider.GetAll().Select(n => new ClienteView(n));
            return View(clienti);
        }

       

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Create(ClienteView cliente)
        {
            try
            {

                if (!_clienteSqlProvider.GetAll().Any(p => p.Email == cliente.Email))
                {
                    _clienteSqlProvider.Insert(cliente.ToCliente());
                }
                else
                {
                    _clienteSqlProvider.Edit(cliente.ToCliente());
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [Route("Cliente/Edit/{IdCliente}")]
       
        public ActionResult Edit(int IdCliente)
        {
            return View(new ClienteView(_clienteSqlProvider.Find(IdCliente)));
        }
        [Route("Cliente/Edit/{IdCliente}")]
        
        [HttpPost]
        public ActionResult Edit(ClienteView cliente)
        {
            try
            {
                _clienteSqlProvider.Edit(cliente.ToCliente());

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
    }
}

CommerceStorage/ProgettoECommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoECommerce.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
      
       public ActionResult GestioneDb()
        {
           
                return View();
           
        }

 
    }
}

CommerceStorage/ProgettoECommerce/Controllers/OrdineController.cs
using ECommerceLibrary;
using ProgettoECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoECommerce.Controllers
{
    public class OrdineController : Controller
    {

        private IOrdineSqlProvider _ordiniSqlProvider;

        public OrdineController()
        {

            _ordiniSqlProvider = new OrdiniSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);

        }
        
        public ActionResult Index()
        {
            var ordini = _ordiniSqlProvider.GetAll().Select(n => new OrdineView(n));
            return View(ordini);
        }
       
      
    }
}

CommerceStorage/ProgettoECommerce/Controllers/PrezzoController.cs
using ECommerceLibrary;
using ProgettoECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoECommerce.Controllers
{
    public class PrezzoController : Controller
    {

        private IPrezzoSqlProvider _prezzoSqlProvider;

        public PrezzoController()
        {

            _prezzoSqlProvider = new PrezzoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);

        }
        
        public ActionResult Index()
        {
            var prezzi = _prezzoSqlProvider.GetAll().Select(n => new PrezzoView(n));
            return View(prezzi);
        }

        

       
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Create(PrezzoView prezzo)
        {
            try
            {
                var b = _prezzoSqlProvider.GetAll().Any(p => p.Paese == prezzo.Paese && p.C8 == prezzo.C8);
                if (b == false)
                {
                    _prezzoSqlProvider.Insert(prezzo.ToPrezzo());
                }
                   
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Route("Prezzo/Edit/{IdPrezzo}")]
        public ActionResult Edit(int IdPrezzo)
        {
            return View(new PrezzoView(_prezzoSqlProvider.Find(IdPrezzo)));
        }

        [Route("Prezzo/Edit/{IdPrezzo}")]
        [HttpPost]
        public ActionResult Edit(PrezzoView prezzo)
        {
            try
            {  
                    _prezzoSqlProvider.Edit(prezzo.ToPrezzo());

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

CommerceStorage/ProgettoECommerce/Controllers/ProdottoController.cs
using ECommerceLibrary;
using ProgettoECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProgettoECommerce.Controllers
{
   
    public class ProdottoController : Controller
    {
        private IProdottoSqlProvider _prodottoSqlProvider;
        private IProducer _producer;

        public ProdottoController(IProducer producer)
        {
		
            _prodottoSqlProvider = new ProdottoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _producer = producer;

    
        }
        
        public ActionResult Index()
        {
            var prodotti = _prodottoSqlProvider.GetAll().Select(n => new ProdottoView(n));
            return View(prodotti);
        }

        public JsonResult Cerca(string parametro)
        {
            var prodotti = _prodottoSqlProvider.Search(parametro);
            return Json(prodotti,JsonRequestBehavior.AllowGet);
        }

        public ActionResult CercaPage()
        {
            return View();
        }

       

       
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Create(ProdottoView prodotto)
        {
            try
            {
                //var prodotti = _prodottoSqlProvider.GetAll();
                //if (prodotti == null)
                //{
                //    prodotto.C8 = "10000000";
                //    _prodottoSqlProvider.Insert(prodotto.ToProdotto());

                //}
                //else
                //{
                //    var c8max = _prodottoSqlProvider.GetMaxC8() + 1;
                //    prodotto.C8 = c8max.ToString();
                //    _prodottoSqlProvider.Insert(prodotto.ToProdotto());
                //}
                _producer.ProduceMessege(prodotto.ToProdotto());
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        [Route("Prodotto/Edit/{IdProdotto}")]
        public ActionResult Edit(int IdProdotto)
        {
            return View(new ProdottoView(_prodottoSqlProvider.Find(IdProdotto)));
        }

        [Route("Prodotto/Edit/{IdProdotto}")]
        [HttpPost]
        public ActionResult Edit(ProdottoView prodotto)
        {
            try
            {
              
                _prodottoSqlProvider.Edit(prodotto.ToProdotto());

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
       
    }
}

CommerceStorage/ProgettoECommerce/Views/Home/GestioneDB.cshtml
@{
    ViewBag.Title = "GestioneDB";
}

<h2>GestioneDB</h2>
<div class="row" style="background-color:white">
    <div class="col-md-3">
        <h2 style="text-align:center">Prodotti</h2>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Index", "Prodotto")'>
                   <h3>Lista</h3>
                </a>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Create", "Prodotto")'>
                    <h3>Crea</h3>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <h2  style="text-align:center">Prezzi</h2>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Index", "Prezzo")'>
                    <h3>Lista</h3>
                </a>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Create", "Prezzo")'>
                    <h3>Crea</h3>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <h2  style="text-align:center">Clienti</h2>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Index", "Cliente")'>
                    <h3>Lista</h3>
                </a>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Create", "Cliente")'>
                    <h3>Crea</h3>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <h2  style="text-align:center">Ordini</h2>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Index", "Ordine")'>
                    <h3>Lista</h3>
                </a>
            </div>
        </div>
    </div>
</div>

CommerceStorage/ProgettoECommerce/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="index">
    <h1>"È stato un uomo saggio colui che ha inventato la birra.”</h1>
    <h3 style="font-style: italic">Platone, filosofo dell’Antica Grecia (428 a.C. – 347 a.C.)</h3>
</div>