CommerceStorage/ProgettoECommerce/Models/CatalogoView.cs
using ECommerceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProgettoECommerce.Models
{
    public class CatalogoView
    {
        public string Titolo { get; set; }

        public string Descrizione { get; set; }

        public string UrlImmagine { get; set; }

        public double PrezzoProdotto { get; set; }

        public string Valuta { get; set; }

        public string Disponibile { get; set; }

        public string C8 { get; set; }

        public int Idprodotto { get; set; }

        public CatalogoView()
        {

        }

        public CatalogoView(Catalogo catalogo)
        {
            Titolo = catalogo.Titolo;
            Descrizione = catalogo.Descrizione;
            UrlImmagine = catalogo.UrlImmagine;
            PrezzoProdotto = catalogo.PrezzoProdotto;
            Valuta = catalogo.Valuta;
            C8 = catalogo.C8;
            Idprodotto = catalogo.IdProdotto;
            if (catalogo.Quantita == 0)
            {
                Disponibile = "Non disponibile";
            }
            else
            {
                Disponibile = "Disponibile";
            }
        }

    }
}

CommerceStorage/ProgettoECommerce/Controllers/CatalogoController.cs
using ECommerceLibrary;
using ProgettoECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ProgettoECommerce.Controllers
{
    public class CatalogoController : Controller
    {
        private ICatalogoSqlProvider _catalogoSqlProvider;
        private IPrezzoSqlProvider _prezziSqlProvider;
        private IOrdineSqlProvider _ordineSqlProvider;
        private IClienteSqlProvider _clienteSqlProvider;
        private IProdottoSqlProvider _prodottoSqlProvider;


        public CatalogoController()
        {

            _catalogoSqlProvider = new CatalogoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _prezziSqlProvider = new PrezzoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _ordineSqlProvider = new OrdiniSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _clienteSqlProvider = new ClientiSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
            _prodottoSqlProvider = new ProdottoSqlProvider(ConfigurationManager.ConnectionStrings["connectionLibrary"].ConnectionString);
        }

        public ActionResult ChangeCountry()
        {
           
            return View();
        }

       
        
        public ActionResult Index(string nazione)
        {
            var catalogo = _catalogoSqlProvider.GetCatalogo(nazione);
            var catalogoView =catalogo.Select(n => new CatalogoView(n)).ToList();
            return View(catalogoView);
        }  



        [HttpGet]
        public JsonResult GetPaesi()
        {
            var paesi = _catalogoSqlProvider.GetPeasi();
           
            
            return Json(paesi, JsonRequestBehavior.AllowGet);
        }


        [Route("Catalogo/Ordina/{c8}/{prezzoProdotto}/{valuta}/{idProdotto}")]

        public ActionResult Ordina(string c8, string prezzoProdotto, string valuta,string idProdotto)
        {
            var cliente = _clienteSqlProvider.GetAll().First();
            var prodotto = _prodottoSqlProvider.Find(Convert.ToInt32(idProdotto));
            if (prodotto.Quantita > 0)
            {
                if (cliente != null)
                {
                    var ordine = new Ordine()
                    {
                        Prezzo = Convert.ToDouble(prezzoProdotto),
                        DataAcquisto = DateTime.Now.Date.ToString("d"),
                        C8 = c8,
                        Valuta = valuta,
                        IdUtente = cliente.IdCliente

                    };
                    _ordineSqlProvider.Insert(ordine);


                    prodotto.Quantita--;
                    _prodottoSqlProvider.Edit(prodotto);


                }
            }

            return RedirectToAction("Index","Ordine");

        }

       
    }
}

CommerceStorage/ProgettoECommerce/Views/Catalogo/ChangeCountry.cshtml
@{
    ViewBag.Title = "ChangeCountry";
}

<h2>ChangeCountry</h2>
<div class="form-horizontal" style="background-color:white">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
           
            <select id="nazioni" class="form-control">
                <option value="" selected="selected"></option>
            </select>
        </div>
    </div>
   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
           
        </div>
    </div>
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jquery")
<script>

        $(document).ready(function () {

            $.ajax({
                url: "/Catalogo/GetPaesi",
                type: "GET",
                success: function (response) {
                    for (var i in response) {
                        var optionpaese = $("<option>");
                        optionpaese.attr("value", response[i].Nome);
                        optionpaese.append(response[i].Nome);
                        $("#nazioni").append(optionpaese)
                    }
                }
            });

            $("#nazioni").change(function () {

                var paese = $("#nazioni").val();

                $.ajax({

                    url:'@Url.Action("Index", "Catalogo")',
                    type: "POST",
                    data: { nazione: paese },
                    success: function (result) {
                        $(function () {
                            $("body").html(result);
                        });
                    }


                });
            });

        });
</script>
}

CommerceStorage/ProgettoECommerce/Views/Catalogo/Index.cshtml
@model IEnumerable<ProgettoECommerce.Models.CatalogoView>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table" style="background-color:white">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titolo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descrizione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlImmagine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrezzoProdotto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valuta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disponibile)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descrizione)
            </td>
            <td>
                <img src="~/Content/Immagini/@item.UrlImmagine" width="100" height="100" )" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrezzoProdotto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valuta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponibile)
            </td>
            <td>
                @if (item.Disponibile == "Disponibile")
                {
                    @Html.ActionLink("Acquista", "Ordina", new { c8 = item.C8, prezzoProdotto = item.PrezzoProdotto, valuta = item.Valuta, idProdotto = item.Idprodotto })
                }


            </td>
        
       
    </tr>
}

</table>